# Generated by Django 4.2.8 on 2024-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_productvariant_is_main_attribute_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brannd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/brand/%Y/%m/%d/"
                    ),
                ),
            ],
        ),
    ]
