# Generated by Django 4.2.8 on 2024-03-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_productvariant_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="amount",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="percent",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="product",
            field=models.ManyToManyField(
                related_name="discounts", to="product.product"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="product_variant",
            field=models.ManyToManyField(
                related_name="discounts", to="product.productvariant"
            ),
        ),
    ]
