# Generated by Django 4.2.8 on 2024-04-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_discount_amount_discount_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="product.attribute",
            ),
        ),
    ]
