# Generated by Django 4.2.8 on 2024-01-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_usermodel_groups_usermodel_user_permissions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="password",
        ),
    ]
