# Generated by Django 4.2.8 on 2024-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_usermodel_admin_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="admin_password",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
