# Generated by Django 4.2.8 on 2024-02-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_image_remove_product_is_available_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="is_main",
        ),
        migrations.AddField(
            model_name="attribute",
            name="category",
            field=models.ManyToManyField(to="product.category"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product/product_main/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=12.12, max_digits=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product/category/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="product.category",
            ),
        ),
    ]
