# Generated by Django 4.2.8 on 2024-04-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_attributevalue_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="category",
            field=models.ManyToManyField(
                related_name="attributes", to="product.category"
            ),
        ),
    ]
